=== mchelen/blueobelisk/structures/trunk/xml/index.dtd
<!-- DTD for index (a list of files and directories) -->

<!-- ENTITY DECLARATIONS -->

<!-- Lang attribute value -->
<!ENTITY % Lang "(en|fr|de|es)">

<!-- Entry type -->
<!ENTITY % entry.type "(dirname|filename)">

<!-- ELEMENT DECLARATION -->

<!-- Root database element -->
<!ELEMENT index (title+,entry+)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
          xml:lang %Lang; "en"
 >

<!-- Entry details -->
<!ELEMENT entry (name*, %entry.type;, synonym*, comments*, authors, date)>
<!ATTLIST entry
          id CDATA #IMPLIED
 >

<!-- Name describing the entry -->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name 
          xml:lang %Lang; "en"
 >

<!-- name of the directory or the filename -->
<!-- directory name -->
<!ELEMENT dirname (#PCDATA)>

<!-- file name -->
<!ELEMENT filename (#PCDATA)>

<!-- Synomyms of the name.
     Each synonym can be localized by using the right lang attribut -->
<!ELEMENT synonym (#PCDATA)>
<!ATTLIST synonym
          xml:lang %Lang;  "en"
 >

<!-- Comments about the entry -->
<!ELEMENT comments (#PCDATA)>
<!ATTLIST comments
          xml:lang %Lang;  "en"
 >

<!-- Comment describing people who's worked on this entry -->
<!ELEMENT authors (#PCDATA)>

<!-- Date of the last entry uptade -->
<!ELEMENT date (#PCDATA)>

=== mchelen/blueobelisk/structures/trunk/src/thiols/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Thiols</title>
  <title xml:lang="de">Thiole</title>
  <title xml:lang="es">Tiols</title>
  <title xml:lang="fr">Thiols</title>
  <title xml:lang="nl">Thiolen</title>
  <title xml:lang="tw">Thiols 硫醇</title>
  <entry id="CS_2-methylproprane-2-thiol">
    <name xml:lang="en">2-Methylproprane-2-thiol</name>
    <name xml:lang="fr">2-Méthylproprane-2-thiol</name>
    <name xml:lang="tw">2-Methylpropane-2-thiol 2-甲基丙烷-2-硫醇</name>
    <filename>2-methylproprane-2-thiol</filename>
    <synonym xml:lang="en">2-Methyl-2-propanethiol</synonym>
    <synonym xml:lang="en">tert-Butyl mercaptan</synonym>
    <synonym xml:lang="fr">2-Méthyl-2-propanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan tert-butylique</synonym>
    <synonym xml:lang="tw">2-Methyl-2-propanethiol 2-甲基-2-丙硫醇</synonym>
    <synonym xml:lang="tw">tert-Butyl mercaptan 三級丁硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_butane-1-thiol">
    <name xml:lang="en">Butane-1-thiol</name>
    <name xml:lang="fr">Butane-1-thiol</name>
    <name xml:lang="tw">Butane-1-thiol 丁-1-硫醇</name>
    <filename>butane-1-thiol</filename>
    <synonym xml:lang="en">1-butanethiol</synonym>
    <synonym xml:lang="en">n-Butyl mercaptan</synonym>
    <synonym xml:lang="fr">1-butanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan n-butylique</synonym>
    <synonym xml:lang="tw">1-butanethiol 1-丁硫醇</synonym>
    <synonym xml:lang="tw">n-Butyl mercaptan 正-丁硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_R_butane-2-thiol">
    <name xml:lang="en">(R)-Butane-2-thiol</name>
    <name xml:lang="fr">(R)-Butane-2-thiol</name>
    <name xml:lang="tw">(R)-Butane-2-thiol (R)-丁-2-硫醇</name>
    <filename>R_butane-2-thiol</filename>
    <synonym xml:lang="en">(R)-2-Butanethiol</synonym>
    <synonym xml:lang="en">sec-Butyl mercaptan</synonym>
    <synonym xml:lang="fr">(R)-2-Butanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan sec-butylique</synonym>
    <synonym xml:lang="tw">(R)-2-Butanethiol (R)-2-丁硫醇</synonym>
    <synonym xml:lang="tw">sec-Butyl mercaptan 二級丁硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_ethane-1_2-dithiol">
    <name xml:lang="en">Ethane-1,2-dithiol</name>
    <name xml:lang="fr">Ethane-1,2-dithiol</name>
    <name xml:lang="tw">Ethane-1,2-dithiol 乙-1,2-二硫醇</name>
    <filename>ethane-1_2-dithiol</filename>
    <synonym xml:lang="en">1,2-Ethanedithiol</synonym>
    <synonym xml:lang="en">1,2-Dimercaptoethane</synonym>
    <synonym xml:lang="fr">1,2-Ethanedithiol</synonym>
    <synonym xml:lang="fr">1,2-Dimercaptoéthane</synonym>
    <synonym xml:lang="tw">1,2-Ethanedithiol 1,2-乙二硫醇</synonym>
    <synonym xml:lang="tw">1,2-Dimercaptoethane 1,2-乙二硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_ethanethiol">
    <name xml:lang="en">Ethanethiol</name>
    <name xml:lang="fr">Ethanethiol</name>
    <name xml:lang="tw">Ethanethiol 乙硫醇</name>
    <filename>ethanethiol</filename>
    <synonym xml:lang="en">Ethyl mercaptan</synonym>
    <synonym xml:lang="fr">Mercaptan éthylique</synonym>
    <synonym xml:lang="tw">Ethyl mercaptan 乙硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_heptane-1-thiol">
    <name xml:lang="en">Heptane-1-thiol</name>
    <name xml:lang="fr">Heptane-1-thiol</name>
    <name xml:lang="tw">Heptane-1-thiol 庚-1-硫醇</name>
    <filename>heptane-1-thiol</filename>
    <synonym xml:lang="en">1-Heptanethiol</synonym>
    <synonym xml:lang="en">Heptyl mercaptan</synonym>
    <synonym xml:lang="fr">1-Heptanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan heptylique</synonym>
    <synonym xml:lang="tw">1-Heptanethiol 1-庚硫醇</synonym>
    <synonym xml:lang="tw">Heptyl mercaptan 庚硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_hexane-1-thiol">
    <name xml:lang="en">Hexane-1-thiol</name>
    <name xml:lang="fr">Hexane-1-thiol</name>
    <name xml:lang="tw">Hexane-1-thiol 己-1-硫醇</name>
    <filename>hexane-1-thiol</filename>
    <synonym xml:lang="en">1-Hexanethiol</synonym>
    <synonym xml:lang="en">Hexyl mercaptan</synonym>
    <synonym xml:lang="fr">1-Hexanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan hexylique</synonym>
    <synonym xml:lang="tw">1-Hexanethiol 1-己硫醇</synonym>
    <synonym xml:lang="tw">Hexyl mercaptan 己硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_methanethiol">
    <name xml:lang="en">Methanethiol</name>
    <name xml:lang="fr">Methanethiol</name>
    <name xml:lang="tw">Methanethiol 甲硫醇</name>
    <filename>methanethiol</filename>
    <synonym xml:lang="en">Methyl mercaptan</synonym>
    <synonym xml:lang="fr">Mercaptan méthylique</synonym>
    <synonym xml:lang="tw">Methyl mercaptan 甲硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_octane-1-thiol">
    <name xml:lang="en">Octane-1-thiol</name>
    <name xml:lang="fr">Octane-1-thiol</name>
    <name xml:lang="tw">Octane-1-thiol 辛-1-硫醇</name>
    <filename>octane-1-thiol</filename>
    <synonym xml:lang="en">1-Octanethiol</synonym>
    <synonym xml:lang="en">Octyl mercaptan</synonym>
    <synonym xml:lang="fr">1-Octanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan octylique</synonym>
    <synonym xml:lang="tw">1-Octanethiol 1-辛硫醇</synonym>
    <synonym xml:lang="tw">Octyl mercaptan 辛硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_pentane-1-thiol">
    <name xml:lang="en">Pentane-1-thiol</name>
    <name xml:lang="fr">Pentane-1-thiol</name>
    <name xml:lang="tw">Pentane-1-thiol 戊-1-硫醇</name>
    <filename>pentane-1-thiol</filename>
    <synonym xml:lang="en">1-Pentanethiol</synonym>
    <synonym xml:lang="en">n-Amyl mercaptan</synonym>
    <synonym xml:lang="fr">1-Pentanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan n-amylique</synonym>
    <synonym xml:lang="tw">1-Pentanethiol 1-戊硫醇</synonym>
    <synonym xml:lang="tw">n-Amyl mercaptan 正-戊基硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_proprane-1-thiol">
    <name xml:lang="en">Proprane-1-thiol</name>
    <name xml:lang="fr">Proprane-1-thiol</name>
    <name xml:lang="tw">Proprane-1-thiol 丙-1-硫醇</name>
    <filename>proprane-1-thiol</filename>
    <synonym xml:lang="en">1-Propanethiol</synonym>
    <synonym xml:lang="en">n-Propyl mercaptan</synonym>
    <synonym xml:lang="fr">1-Propanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan n-propylique</synonym>
    <synonym xml:lang="tw">1-Propanethiol 1-丙硫醇</synonym>
    <synonym xml:lang="tw">n-Propyl mercaptan 正-丙硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_proprane-2-thiol">
    <name xml:lang="en">Proprane-2-thiol</name>
    <name xml:lang="fr">Proprane-2-thiol</name>
    <name xml:lang="tw">Proprane-2-thiol 丙-2-硫醇</name>
    <filename>proprane-2-thiol</filename>
    <synonym xml:lang="en">2-Propanethiol</synonym>
    <synonym xml:lang="en">Isopropyl mercaptan</synonym>
    <synonym xml:lang="fr">2-Propanethiol</synonym>
    <synonym xml:lang="fr">Mercaptan isopropylique</synonym>
    <synonym xml:lang="tw">2-Propanethiol 2-丙硫醇</synonym>
    <synonym xml:lang="tw">Isopropyl mercaptan 異丙硫醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/tags/2.2.0/src/thioethers/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Thioethers</title>
  <title xml:lang="de">Thioether</title>
  <title xml:lang="es">Tioéters</title>
  <title xml:lang="fr">Thioéthers</title>
  <title xml:lang="nl">Thioethers</title>
  <title xml:lang="tw">Thioethers 硫醚類</title>
  <entry id="CS_thiepin">
    <name xml:lang="en">Thiepin</name>
    <name xml:lang="fr">Thiépine</name>
    <name xml:lang="tw">Thiepin 暫譯為: 一硫柒圜 (含硫雜環)</name>
    <filename>thiepin</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_thiophene">
    <name xml:lang="en">Thiophene</name>
    <name xml:lang="fr">Thiophène</name>
    <name xml:lang="tw">Thiophene 噻吩/一硫二烯伍圜</name>
    <filename>thiophene</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/peptides/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Peptides</title>
  <title xml:lang="es">Péptidos</title>
  <title xml:lang="de">Peptide</title>
  <title xml:lang="fr">Peptides</title>
  <title xml:lang="nl">Peptiden</title>
  <title xml:lang="tw">Peptides 多肽</title>
  <entry id="CS_aspartame">
    <name xml:lang="en">Aspartame</name>
    <name xml:lang="fr">Aspartame</name>
    <name xml:lang="tw">Aspartame 阿斯巴甜 (雙肽甜味料)</name>
    <filename>aspartame</filename>
    <synonym xml:lang="en">L-Aspartyl-L-phenylalanine methyl ester</synonym>
    <synonym xml:lang="fr">Ester méthylique de L-aspartyl-L-phénylalanine</synonym>
    <synonym xml:lang="tw">L-Aspartyl-L-phenylalanine methyl ester 天門冬醯-L-苯丙胺酸甲酯</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2009-07-06</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/amides/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Amides</title>
  <title xml:lang="fr">Amides</title>
  <title xml:lang="de">Amide</title>
  <entry id="CS_N_N-dimethylformamide">
    <name xml:lang="en">N,N-Dimethylformamide</name>
    <name xml:lang="de">N,N-Dimethylformamid</name>
    <filename>N_N-dimethylformamide</filename>
    <synonym xml:lang="en">DMF</synonym>
    <synonym xml:lang="de">DMF</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_oxamide">
    <name xml:lang="en">Oxamide</name>
    <name xml:lang="de">Oxamid</name>
    <filename>oxamide</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_1-bromopyrrolidine-2_5-dione">
    <name xml:lang="en">1-Bromopyrrolidine-2,5-dione</name>
    <filename>1-bromopyrrolidine-2_5-dione</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_acetamide">
    <name xml:lang="en">Acetamide</name>
    <filename>acetamide</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_ethyl_carbamate">
    <name xml:lang="en">Ethyl carbamate</name>
    <filename>ethyl_carbamate</filename>
    <synonym xml:lang="en">Urethane</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_N_N-dimethylacetamide">
    <name xml:lang="en">N,N-Dimethylacetamide</name>
    <name xml:lang="fr">N,N-Diméthylacétamide</name>
    <filename>N_N-dimethylacetamide</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>

</index>

=== mchelen/blueobelisk/structures/trunk/src/thioethers/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Thioethers</title>
  <title xml:lang="fr">Thio√©thers</title>
  <title xml:lang="de">Thioether</title>
  <entry id="CS_thiepin">
    <name xml:lang="en">Thiepin</name>
    <filename>thiepin</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_thiophene">
    <name xml:lang="en">Thiophene</name>
    <filename>thiophene</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/esters/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Esters</title>
  <title xml:lang="fr">Esters</title>
  <title xml:lang="de">Ester</title>
  <entry id="CS_ethyl_acetate">
    <name xml:lang="en">Ethyl acetate</name>
    <filename>ethyl_acetate</filename>
    <synonym xml:lang="en">Acetic acid ethyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_butyl_acetate">
    <name xml:lang="en">Butyl acetate</name>
    <filename>butyl_acetate</filename>
    <synonym xml:lang="en">Acetic acid n-butyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_butyl_butanoate">
    <name xml:lang="en">Butyl butanoate</name>
    <filename>butyl_butanoate</filename>
    <synonym xml:lang="en">n-Butyric acid n-butyl ester</synonym>
    <synonym xml:lang="en">Butyl butyrate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_butyl_formate">
    <name xml:lang="en">Butyl formate</name>
    <filename>butyl_formate</filename>
    <synonym xml:lang="en">Formic acid n-butyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_butyl_pentanoate">
    <name xml:lang="en">Butyl pentanoate</name>
    <filename>butyl_pentanoate</filename>
    <synonym xml:lang="en">n-Valeric acid n-butyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_butyl_propanoate">
    <name xml:lang="en">Butyl propanoate</name>
    <filename>butyl_propanoate</filename>
    <synonym xml:lang="en">Propionic acid n-butyl ester</synonym>
    <synonym xml:lang="en">Butyl propionate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_ethyl_butanoate">
    <name xml:lang="en">Ethyl butanoate</name>
    <filename>ethyl_butanoate</filename>
    <synonym xml:lang="en">n-Butyric acid ethyl ester</synonym>
    <synonym xml:lang="en">Ethyl Butyrate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_ethyl_formate">
    <name xml:lang="en">Ethyl formate</name>
    <filename>ethyl_formate</filename>
    <synonym xml:lang="en">Formic acid ethyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_ethyl_pentanoate">
    <name xml:lang="en">Ethyl pentanoate</name>
    <filename>ethyl_pentanoate</filename>
    <synonym xml:lang="en">n-Valeric acid ethyl ester</synonym>
    <synonym xml:lang="en">Ethyl valerate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_ethyl_propanoate">
    <name xml:lang="en">Ethyl propanoate</name>
    <filename>ethyl_propanoate</filename>
    <synonym xml:lang="en">Propionic acid ethyl ester</synonym>
    <synonym xml:lang="en">Ethyl propionate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_methyl_acetate">
    <name xml:lang="en">Methyl acetate</name>
    <filename>methyl_acetate</filename>
    <synonym xml:lang="en">Acetic acid methyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_methyl_butanoate">
    <name xml:lang="en">Methyl butanoate</name>
    <filename>methyl_butanoate</filename>
    <synonym xml:lang="en">n-Butyric acid methyl ester</synonym>
    <synonym xml:lang="en">Methyl butyrate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_methyl_formate">
    <name xml:lang="en">Methyl formate</name>
    <filename>methyl_formate</filename>
    <synonym xml:lang="en">Formic acid methyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_methyl_pentanoate">
    <name xml:lang="en">Methyl pentanoate</name>
    <filename>methyl_pentanoate</filename>
    <synonym xml:lang="en">n-Valeric acid methyl ester</synonym>
    <synonym xml:lang="en">Methyl valerate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_methyl_propanoate">
    <name xml:lang="en">Methyl propanoate</name>
    <filename>methyl_propanoate</filename>
    <synonym xml:lang="en">Propionic acid methyl ester</synonym>
    <synonym xml:lang="en">Methyl propionate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_pentyl_acetate">
    <name xml:lang="en">Pentyl acetate</name>
    <filename>pentyl_acetate</filename>
    <synonym xml:lang="en">Acetic acid pentyl ester</synonym>
    <synonym xml:lang="en">Amyl acetate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_pentyl_butanoate">
    <name xml:lang="en">Pentyl butanoate</name>
    <filename>pentyl_butanoate</filename>
    <synonym xml:lang="en">n-Butyric acid pentyl ester</synonym>
    <synonym xml:lang="en">Pentyl butyrate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_pentyl_formate">
    <name xml:lang="en">Pentyl formate</name>
    <filename>pentyl_formate</filename>
    <synonym xml:lang="en">Formic acid pentyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_pentyl_pentanoate">
    <name xml:lang="en">Pentyl pentanoate</name>
    <filename>pentyl_pentanoate</filename>
    <synonym xml:lang="en">n-Valeric acid pentyl ester</synonym>
    <synonym xml:lang="en">Pentyl valerate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_pentyl_propanoate">
    <name xml:lang="en">Pentyl propanoate</name>
    <filename>pentyl_propanoate</filename>
    <synonym xml:lang="en">Propionic acid pentyl ester</synonym>
    <synonym xml:lang="en">Pentyl propionate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_propyl_acetate">
    <name xml:lang="en">Propyl acetate</name>
    <filename>propyl_acetate</filename>
    <synonym xml:lang="en">Acetic acid propyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_propyl_butanoate">
    <name xml:lang="en">Propyl butanoate</name>
    <filename>propyl_butanoate</filename>
    <synonym xml:lang="en">n-Butyric acid propyl ester</synonym>
    <synonym xml:lang="en">Propyl butyrate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_propyl_formate">
    <name xml:lang="en">Propyl formate</name>
    <filename>propyl_formate</filename>
    <synonym xml:lang="en">Formic acid propyl ester</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_propyl_pentanoate">
    <name xml:lang="en">Propyl pentanoate</name>
    <filename>propyl_pentanoate</filename>
    <synonym xml:lang="en">n-Valeric acid propyl ester</synonym>
    <synonym xml:lang="en">Propyl valerate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_propyl_propanoate">
    <name xml:lang="en">Propyl propanoate</name>
    <filename>propyl_propanoate</filename>
    <synonym xml:lang="en">Propionic acid propyl ester</synonym>
    <synonym xml:lang="en">Propyl propionate</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_linolein">
    <name xml:lang="en">2,3-bis[[(9Z,12Z)-octadeca-9,12-dienoyl]oxy]propyl (9Z,12Z)-octadeca-9,12-dienoate</name>
    <filename>linolein</filename>
    <synonym xml:lang="en">Linolein</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-06-27</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/tags/2.2.0/trunk/src/carbamides/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Carbamides</title>
  <title xml:lang="de">Carbamides</title>
  <title xml:lang="es">Carbamidas</title>
  <title xml:lang="fr">Carbamides</title>
  <title xml:lang="nl">Carbamides</title>
  <title xml:lang="tw">Carbamides 羰基胺類</title>
  <entry id="CS_urea">
    <name xml:lang="en">Urea</name>
    <name xml:lang="de">Harnstoff</name>
    <name xml:lang="fr">Urée</name>
    <name xml:lang="tw">Urea 尿素</name>
    <filename>urea</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-13</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/carbamides/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Carbamides</title>
  <title xml:lang="de">Carbamides</title>
  <title xml:lang="fr">Carbamides</title>
  <entry id="CS_urea">
    <name xml:lang="en">Urea</name>
    <name xml:lang="de">Harnstoff</name>
    <name xml:lang="fr">UrÃ©e</name>
    <filename>urea</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-13</date>
  </entry>
</index>
