=== mchelen/blueobelisk/structures/trunk/xml/index.dtd
<!-- DTD for index (a list of files and directories) -->

<!-- ENTITY DECLARATIONS -->

<!-- Lang attribute value -->
<!ENTITY % Lang "(en|fr|de|es)">

<!-- Entry type -->
<!ENTITY % entry.type "(dirname|filename)">

<!-- ELEMENT DECLARATION -->

<!-- Root database element -->
<!ELEMENT index (title+,entry+)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
          xml:lang %Lang; "en"
 >

<!-- Entry details -->
<!ELEMENT entry (name*, %entry.type;, synonym*, comments*, authors, date)>
<!ATTLIST entry
          id CDATA #IMPLIED
 >

<!-- Name describing the entry -->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name 
          xml:lang %Lang; "en"
 >

<!-- name of the directory or the filename -->
<!-- directory name -->
<!ELEMENT dirname (#PCDATA)>

<!-- file name -->
<!ELEMENT filename (#PCDATA)>

<!-- Synomyms of the name.
     Each synonym can be localized by using the right lang attribut -->
<!ELEMENT synonym (#PCDATA)>
<!ATTLIST synonym
          xml:lang %Lang;  "en"
 >

<!-- Comments about the entry -->
<!ELEMENT comments (#PCDATA)>
<!ATTLIST comments
          xml:lang %Lang;  "en"
 >

<!-- Comment describing people who's worked on this entry -->
<!ELEMENT authors (#PCDATA)>

<!-- Date of the last entry uptade -->
<!ELEMENT date (#PCDATA)>

=== mchelen/blueobelisk/structures/trunk/src/polycyclic_alkanes/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Polycyclic alkanes</title>
  <title xml:lang="de">Polyzyklische Alkane</title>
  <title xml:lang="es">Alcanos policíclicos</title>
  <title xml:lang="fr">Alcanes polycycliques</title>
  <title xml:lang="nl">Polycyclische Alkanen</title>
  <title xml:lang="tw">Polycyclic alkanes 多環烷類</title>
  <entry id="CS_cis-decahydronaphthalene">
    <name xml:lang="en">cis-Decahydronaphthalene</name>
    <name xml:lang="fr">cis-Décahydronaphthalène</name>
    <name xml:lang="tw">cis-Decahydronaphthalene 順十氫萘/順十氫化萘</name>
    <filename>cis-decahydronaphthalene</filename>
    <synonym xml:lang="en">cis-Decalin</synonym>
    <synonym xml:lang="fr">cis-Décaline</synonym>
    <synonym xml:lang="tw">cis-Decalin 順十氫萘/順十氫化萘</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_trans-decahydronaphthalene">
    <name xml:lang="en">trans-Decahydronaphthalene</name>
    <name xml:lang="fr">trans-Décahydronaphthalène</name>
    <name xml:lang="tw">trans-Decahydronaphthalene 反十氫萘/反十氫化萘</name>
    <filename>trans-decahydronaphthalene</filename>
    <synonym xml:lang="en">trans-Decalin</synonym>
    <synonym xml:lang="fr">trans-Décaline</synonym>
    <synonym xml:lang="tw">trans-Decalin 反十氫萘/反十氫化萘</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_hexadecahydro-1H-cyclopenta_a_phenanthrene">
    <name xml:lang="en">Hexadecahydro-1H-cyclopenta[a]phenanthrene</name>
    <name xml:lang="fr">Hexadecahydro-1H-cyclopenta[a]phenanthrène</name>
    <name xml:lang="tw">Hexadecahydro-1H-cyclopenta[a]phenanthrene 16氫-1氫-環戊烷并[a]菲</name>
    <filename>hexadecahydro-1H-cyclopenta_a_phenanthrene</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_abietic_acid">
    <name xml:lang="en">Abietic acid</name>
    <name xml:lang="de">Abietinsäure</name>
    <name xml:lang="fr">Acide abiétique</name>
    <name xml:lang="tw">Abietic acid 松脂酸</name>
    <filename>abietic_acid</filename>
    <synonym xml:lang="en">Sylvic acid</synonym>
    <synonym xml:lang="en">Abietinic acid</synonym>
    <synonym xml:lang="de">Sylvinsäure</synonym>
    <synonym xml:lang="fr">Acide sylvitique</synonym>
    <synonym xml:lang="fr">Acide abiétinique</synonym>
    <synonym xml:lang="tw">Sylvic acid 松香酸</synonym>
    <synonym xml:lang="tw">Abietinic acid 松脂酸</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_1R_4S-1_7_7-trimethylnorbornan-2-one">
    <name xml:lang="en">(1R)-Camphor</name>
    <name xml:lang="fr">(1R)-Camphor</name>
    <name xml:lang="tw">(1R)-Camphor (1R)-樟腦</name>
    <filename>1R-camphor</filename>
    <synonym xml:lang="en">(1R,4S)-1,7,7-Trimethylnorbornan-2-one</synonym>
    <synonym xml:lang="en">D-Camphor</synonym>
    <synonym xml:lang="fr">(1R,4S)-1,7,7-Triméthylnorbornan-2-one</synonym>
    <synonym xml:lang="fr">D-Camphor</synonym>
    <synonym xml:lang="tw">(1R,4S)-1,7,7-Trimethylnorbornan-2-one (1R,4S)-1,7,7-三甲基降樟腦</synonym>
    <synonym xml:lang="tw">D-Camphor D-樟腦</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_1R_4S-2_2-dimethyl-3-methylidenenorbornane">
    <name xml:lang="en">(1R)-Camphene</name>
    <name xml:lang="fr">(1R)-Camphène</name>
    <name xml:lang="tw">(1R)-Camphene 莰烯/松精油/樟腦精</name>
    <filename>1R-camphene</filename>
    <synonym xml:lang="en">(1R,4S)-2,2-Dimethyl-3-methylidenenorbornane</synonym>
    <synonym xml:lang="en">D-Camphene</synonym>
    <synonym xml:lang="fr">(1R,4S)-2,2-Diméthyl-3-méthylidènenorbornane</synonym>
    <synonym xml:lang="fr">D-Camphène</synonym>
    <synonym xml:lang="tw">(1R,4S)-2,2-Dimethyl-3-methylidenenorbornane (1R,4S)-2,2-二甲基-3-亞甲基降莰烷</synonym>
    <synonym xml:lang="tw">D-Camphene 莰烯</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_cubane">
    <name xml:lang="en">Cubane</name>
    <name xml:lang="fr">Cubane</name>
    <name xml:lang="tw">Cubane 立方體烷</name>
    <filename>cubane</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_bicyclo_2_2_1_heptane">
    <name xml:lang="en">Norbornane</name>
    <name xml:lang="fr">Norbornane</name>
    <name xml:lang="tw">Norbornane 降莰烷</name>
    <filename>norbornane</filename>
    <synonym xml:lang="en">Bicyclo[2.2.1]heptane</synonym>
    <synonym xml:lang="fr">Bicyclo[2.2.1]heptane</synonym>
    <synonym xml:lang="tw">Bicyclo[2.2.1]heptane 雙環[2.2.1]庚烷</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2007-12-03</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/natural_products/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Natural products</title>
  <title xml:lang="de">Naturstoff</title>
  <title xml:lang="es">Sustancias naturales</title>
  <title xml:lang="fr">Substances naturelles</title>
  <title xml:lang="nl">Natuurlijke chemicaliën</title>
  <title xml:lang="tw">Natural products 天然產物/化合物</title>
  <entry id="CS_coelenterazine">
    <name xml:lang="en">Coelenterazine</name>
    <name xml:lang="fr">Coelentérazine</name>
    <name xml:lang="tw">Coelenterazine 腔腸素</name>
    <filename>coelenterazine</filename>
    <synonym xml:lang="en">Renilla luciferin</synonym>
    <synonym xml:lang="fr">Luciférine de Renilla reniformis</synonym>
    <synonym xml:lang="tw">Renilla luciferin 水母螢光素</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2009-07-06</date>
  </entry>
  <entry id="CS_D-luciferin">
    <name xml:lang="en">D-Luciferin</name>
    <name xml:lang="fr">D-Luciférine</name>
    <name xml:lang="tw">D-Luciferin 螢蟲素</name>
    <filename>D-luciferin</filename>
    <synonym xml:lang="en">Firefly luciferin</synonym>
    <synonym xml:lang="fr">Luciférine de luciole</synonym>
    <synonym xml:lang="tw">Firefly luciferin 螢火蟲螢光素</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2009-07-06</date>
  </entry>
  <entry id="CS_norepinephrine">
    <name xml:lang="en">Norepinephrine</name>
    <name xml:lang="fr">Norépinéphrine</name>
    <name xml:lang="tw">Norepinephrine 正腎上腺素</name>
    <filename>norepinephrine</filename>
    <synonym xml:lang="en">Noradrenaline</synonym>
    <synonym xml:lang="fr">Noradrénaline</synonym>
    <synonym xml:lang="tw">Noradrenaline 降腎上腺素</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2009-07-06</date>
  </entry>
  <entry id="CS_R-adrenaline">
    <name xml:lang="en">R-Adrenaline</name>
    <name xml:lang="fr">R-Adrénaline</name>
    <name xml:lang="tw">R-Adrenaline R-腎上腺素</name>
    <filename>R-adrenaline</filename>
    <authors>Jerome Pansanel</authors>
    <date>2009-07-06</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/aldehydes/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Aldehydes</title>
  <title xml:lang="de">Aldehyde</title>
  <title xml:lang="es">Aldehídos</title>
  <title xml:lang="fr">Aldéhydes</title>
  <title xml:lang="nl">Aldehyden</title>
  <title xml:lang="tw">Aldehydes 醛類</title>
  <entry id="CS_2-methylpropanal">
    <name xml:lang="en">2-Methylpropanal</name>
    <name xml:lang="fr">2-Méthylpropanal</name>
    <name xml:lang="tw">2-Methylpropanal 2-甲基丙醛</name>
    <filename>2-methylpropanal</filename>
    <synonym xml:lang="en">Isobutyraldehyde</synonym>
    <synonym xml:lang="de">Isobutyraldehyd</synonym>
    <synonym xml:lang="fr">Aldéhyde isobutyrique</synonym>
    <synonym xml:lang="tw">Isobutyraldehyde 異丁醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_2R-2-methylbutanal">
    <name xml:lang="en">(2R)-2-Methylbutanal</name>
    <name xml:lang="fr">(2R)-2-Méthylbutanal</name>
    <name xml:lang="tw">(2R)-2-Methylbutanal (2R)-2-甲基丁醛</name>
    <filename>2R-2-methylbutanal</filename>
    <synonym xml:lang="en">2-Methylbutyraldehyde</synonym>
    <synonym xml:lang="de">2-Methylbutyraldehyd</synonym>
    <synonym xml:lang="fr">2-Méthylbutyraldéhyde</synonym>
    <synonym xml:lang="tw">2-Methylbutyraldehyde 2-甲基丁醛</synonym>
    <synonym xml:lang="fr">Aldéhyde 2-méthylbutyrique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_3-methylbutanal">
    <name xml:lang="en">3-Methylbutanal</name>
    <name xml:lang="fr">3-Méthylbutanal</name>
    <name xml:lang="tw">3-Methylbutanal 3-甲基丁醛</name>
    <filename>3-methylbutanal</filename>
    <synonym xml:lang="en">Isovaleraldehyde</synonym>
    <synonym xml:lang="de">Isovaleraldehyd</synonym>
    <synonym xml:lang="fr">Aldéhyde isovalérique</synonym>
    <synonym xml:lang="tw">Isovaleraldehyde 異戊醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_butanal">
    <name xml:lang="en">Butanal</name>
    <name xml:lang="de">Butanal</name>
    <name xml:lang="fr">Butanal</name>
    <name xml:lang="tw">Butanal 丁醛</name>
    <filename>butanal</filename>
    <synonym xml:lang="en">n-Butyraldehyde</synonym>
    <synonym xml:lang="de">n-Butyraldehyd</synonym>
    <synonym xml:lang="fr">n-Butyraldéhyde</synonym>
    <synonym xml:lang="fr">Aldéhyde butyrique</synonym>
    <synonym xml:lang="tw">n-Butyraldehyde 正-丁醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_acetaldehyde">
    <name xml:lang="en">Acetaldehyde</name>
    <name xml:lang="fr">Acétaldéhyde</name>
    <name xml:lang="tw">Acetaldehyde 乙醛</name>
    <filename>acetaldehyde</filename>
    <synonym xml:lang="en">Ethanal</synonym>
    <synonym xml:lang="fr">Ethanal</synonym>
    <synonym xml:lang="tw">Ethanal 乙醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_heptanal">
    <name xml:lang="en">Heptanal</name>
    <name xml:lang="fr">Heptanal</name>
    <name xml:lang="tw">Heptanal 庚醛</name>
    <filename>heptanal</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_hexanal">
    <name xml:lang="en">Hexanal</name>
    <name xml:lang="fr">Hexanal</name>
    <name xml:lang="tw">Hexanal 已醛</name>
    <filename>hexanal</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_formaldehyde">
    <name xml:lang="en">Formaldehyde</name>
    <name xml:lang="fr">Formaldéhyde</name>
    <name xml:lang="de">Formaldehyd</name>
    <name xml:lang="tw">Formaldehyde 甲醛</name>
    <filename>formaldehyde</filename>
    <synonym xml:lang="en">Methanal</synonym>
    <synonym xml:lang="fr">Méthanal</synonym>
    <synonym xml:lang="tw">Methanal 甲醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_octanal">
    <name xml:lang="en">Octanal</name>
    <name xml:lang="fr">Octanal</name>
    <name xml:lang="tw">Octanal 辛醛</name>
    <filename>octanal</filename>
    <synonym xml:lang="en">Octyl aldehyde</synonym>
    <synonym xml:lang="de">Octylaldehyd</synonym>
    <synonym xml:lang="fr">Aldéhyde octylique</synonym>
    <synonym xml:lang="tw">Octyl aldehyde 辛醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_pentanal">
    <name xml:lang="en">Pentanal</name>
    <name xml:lang="fr">Pentanal</name>
    <name xml:lang="tw">Pentanal 戊醛</name>
    <filename>pentanal</filename>
    <synonym xml:lang="en">n-Valeraldehyde</synonym>
    <synonym xml:lang="de">n-Valeraldehyd</synonym>
    <synonym xml:lang="fr">n-Valéraldéhyde</synonym>
    <synonym xml:lang="fr">Aldéhyde valérique</synonym>
    <synonym xml:lang="tw">n-Valeraldehyde 正戊醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_propanal">
    <name xml:lang="en">Propanal</name>
    <name xml:lang="fr">Propanal</name>
    <name xml:lang="tw">Propanal 丙醛</name>
    <filename>propanal</filename>
    <synonym xml:lang="en">Proprionaldehyde</synonym>
    <synonym xml:lang="de">Proprionaldehyd</synonym>
    <synonym xml:lang="fr">Proprionaldéhyde</synonym>
    <synonym xml:lang="fr">Aldéhyde proprionique</synonym>
    <synonym xml:lang="tw">Proprionaldehyde 丙醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_prop-2-enal">
    <name xml:lang="en">Prop-2-enal</name>
    <name xml:lang="fr">Prop-2-enal</name>
    <name xml:lang="tw">Prop-2-enal 丙-2-烯醛</name>
    <filename>prop-2-enal</filename>
    <synonym xml:lang="en">Acrolein</synonym>
    <synonym xml:lang="fr">Acroléine</synonym>
    <synonym xml:lang="tw">Acrolein 丙烯醛</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-21</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/water/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Water</title>
  <title xml:lang="de">Wasser</title>
  <title xml:lang="es">Agua</title>
  <title xml:lang="fr">Eau</title>
  <title xml:lang="nl">Water</title>
  <title xml:lang="tw">Water 水</title>
  <entry id="CS_oxidane">
    <name xml:lang="en">Water</name>
    <name xml:lang="de">Wasser</name>
    <name xml:lang="fr">Eau</name>
    <name xml:lang="tw">Water 水</name>
    <filename>water</filename>
    <synonym xml:lang="en">Oxidane</synonym>
    <synonym xml:lang="de">Oxidan</synonym>
    <synonym xml:lang="fr">Oxidane</synonym>
    <synonym xml:lang="tw">Oxidane 氧烷</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/drugs/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Drugs</title>
  <title xml:lang="fr">Drogues</title>
  <title xml:lang="de">Drogen</title>
  <entry id="CS_4-acetamidophenyl_2-hydroxybenzoate">
    <name xml:lang="en">(4-Acetamidophenyl) 2-hydroxybenzoate</name>
    <filename>4-acetamidophenyl_2-hydroxybenzoate</filename>
    <synonym xml:lang="en">Acetaminosalol</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_N-4-hydroxyphenyl_acetamide">
    <name xml:lang="en">N-(4-Hydroxyphenyl)acetamide</name>
    <filename>N-4-hydroxyphenyl_acetamide</filename>
    <synonym xml:lang="en">Acetaminophen</synonym>
    <synonym xml:lang="en">Paracetamol</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_acepromazine">
    <name xml:lang="en">Acepromazine</name>
    <filename>acepromazine</filename>
    <synonym xml:lang="en">Acetylpromazine</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_2S-1-phenylpropan-2-amine">
    <name xml:lang="en">(2S)-1-Phenylpropan-2-amine</name>
    <filename>2S-1-phenylpropan-2-amine</filename>
    <synonym xml:lang="en">Dextroamphetamine</synonym>
    <synonym xml:lang="en">D-Amphetamine</synonym>
    <synonym xml:lang="fr">Dextroamphétamine</synonym>
    <synonym xml:lang="fr">D-Amphétamine</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-24</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/tags/2.2.0/src/nucleobases/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Nucleobases</title>
  <title xml:lang="de">Nukleobasen</title>
  <title xml:lang="es">Nucleobases</title>
  <title xml:lang="fr">Bases nucléiques</title>
  <title xml:lang="nl">Nucleotiden</title>
  <title xml:lang="tw">Nucleobases 鹼基/核鹼基</title>
  <entry id="CS_1H-pyrimidine-2_4-dione">
    <name xml:lang="en">Uracil</name>
    <name xml:lang="de">Uracil</name>
    <name xml:lang="fr">Uracile</name>
    <name xml:lang="tw">Uracil 尿嘧啶</name>
    <filename>uracil</filename>
    <synonym xml:lang="en">1H-Pyrimidine-2,4-dione</synonym>
    <synonym xml:lang="fr">1H-Pyrimidine-2,4-dione</synonym>
    <synonym xml:lang="tw">1H-Pyrimidine-2,4-dione 1氫-嘧啶-2, 4-二酮</synonym>
    <abbrev>U</abbrev>
    <authors>Jerome Pansanel</authors>
    <date>2006-09-28</date>
  </entry>
  <entry id="CS_2-amino-3_7-dihydropurin-6-one">
    <name xml:lang="en">Guanine</name>
    <name xml:lang="de">Guanin</name>
    <name xml:lang="es">Guanina</name>
    <name xml:lang="fr">Guanine</name>
    <name xml:lang="tw">Guanine 鳥嘌呤</name>
    <filename>guanine</filename>
    <synonym xml:lang="en">2-Amino-3,7-dihydropurin-6-one</synonym>
    <synonym xml:lang="fr">2-Amino-3,7-dihydropurin-6-one</synonym>
    <synonym xml:lang="tw">2-Amino-3,7-dihydropurin-6-one 2-胺基-3, 7-二氫嘌呤-6-酮</synonym>
    <abbrev>G</abbrev>
    <authors>Jerome Pansanel</authors>
    <date>2006-09-28</date>
  </entry>
  <entry id="CS_4-amino-3H-pyrimidin-2-one">
    <name xml:lang="en">Cytosine</name>
    <name xml:lang="de">Cytosin</name>
    <name xml:lang="es">Cytosina</name>
    <name xml:lang="fr">Cytosine</name>
    <name xml:lang="tw">Cytosine 胞嘧啶</name>
    <filename>cytosine</filename>
    <synonym xml:lang="en">4-Amino-3H-pyrimidin-2-one</synonym>
    <synonym xml:lang="fr">4-Amino-3H-pyrimidin-2-one</synonym>
    <synonym xml:lang="fr">C</synonym>
  <synonym xml:lang="tw">4-Amino-3H-pyrimidin-2-one 4-胺基-3氫-嘧啶-2-酮</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-09-28</date>
  </entry>
  <entry id="CS_5-methyl-1H-pyrimidine-2_4-dione">
    <name xml:lang="en">Thymine</name>
    <name xml:lang="de">Thymine</name>
    <name xml:lang="fr">Thymine</name>
    <name xml:lang="tw">Thymine 胸嘧啶</name>
    <filename>thymine</filename>
    <synonym xml:lang="en">5-Methyl-1H-pyrimidine-2,4-dione</synonym>
    <synonym xml:lang="fr">5-Methyl-1H-pyrimidine-2,4-dione</synonym>
    <synonym xml:lang="tw">5-Methyl-1H-pyrimidine-2,4-dione 5-甲基-1氫-嘧啶-2, 4-二酮</synonym>
    <abbrev>T</abbrev>
    <authors>Jerome Pansanel</authors>
    <date>2006-09-28</date>
  </entry>
  <entry id="CS_7H-purin-6-amine">
    <name xml:lang="en">Adenine</name>
    <name xml:lang="de">Adenin</name>
    <name xml:lang="es">Adenina</name>
    <name xml:lang="fr">Adénine</name>
    <name xml:lang="tw">Adenine 腺嘌呤</name>
    <filename>adenine</filename>
    <synonym xml:lang="en">7H-Purin-6-amine</synonym>
    <synonym xml:lang="fr">7H-Purin-6-amine</synonym>
    <synonym xml:lang="tw">7H-Purin-6-amine 7氫-嘌呤-6-胺</synonym>
    <abbrev>A</abbrev>
    <authors>Jerome Pansanel</authors>
    <date>2006-09-28</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/sulfones/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Sulfones</title>
  <title xml:lang="fr">Sulfones</title>
  <title xml:lang="de">Sulfone</title>
  <entry id="CS_4-methylbenzenesulfonic_acid">
    <name xml:lang="en">4-Methylbenzenesulfonic acid</name>
    <filename>4-methylbenzenesulfonic_acid</filename>
    <synonym xml:lang="en">p-Toluenesulfonic acid</synonym>
    <synonym xml:lang="en">PTSA</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_benzenesulfonic_acid">
    <name xml:lang="en">Benzenesulfonic acid</name>
    <filename>benzenesulfonic_acid</filename>
    <synonym xml:lang="en"></synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_methanesulfonic_acid">
    <name xml:lang="en">Methanesulfonic acid</name>
    <filename>methanesulfonic_acid</filename>
    <synonym xml:lang="en">Methylsulfonic acid</synonym>
    <synonym xml:lang="en">MSA</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/alkynes/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Alkynes</title>
  <title xml:lang="fr">Alcynes</title>
  <title xml:lang="de">Alkine</title>
  <entry id="CS_acetylene">
    <name xml:lang="en">Acetylene</name>
    <filename>acetylene</filename>
    <synonym xml:lang="en">Ethyne</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_but-1-yne">
    <name xml:lang="en">But-1-yne</name>
    <filename>but-1-yne</filename>
    <synonym xml:lang="en">1-Butyne</synonym>
    <synonym xml:lang="de">1-Butin</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_but-2-yne">
    <name xml:lang="en">But-2-yne</name>
    <filename>but-2-yne</filename>
    <synonym xml:lang="en">2-Butyne</synonym>
    <synonym xml:lang="de">2-Butin</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_propyne">
    <name xml:lang="en">Propyne</name>
    <filename>propyne</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
</index>
