=== mchelen/blueobelisk/structures/trunk/xml/index.dtd
<!-- DTD for index (a list of files and directories) -->

<!-- ENTITY DECLARATIONS -->

<!-- Lang attribute value -->
<!ENTITY % Lang "(en|fr|de|es)">

<!-- Entry type -->
<!ENTITY % entry.type "(dirname|filename)">

<!-- ELEMENT DECLARATION -->

<!-- Root database element -->
<!ELEMENT index (title+,entry+)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
          xml:lang %Lang; "en"
 >

<!-- Entry details -->
<!ELEMENT entry (name*, %entry.type;, synonym*, comments*, authors, date)>
<!ATTLIST entry
          id CDATA #IMPLIED
 >

<!-- Name describing the entry -->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name 
          xml:lang %Lang; "en"
 >

<!-- name of the directory or the filename -->
<!-- directory name -->
<!ELEMENT dirname (#PCDATA)>

<!-- file name -->
<!ELEMENT filename (#PCDATA)>

<!-- Synomyms of the name.
     Each synonym can be localized by using the right lang attribut -->
<!ELEMENT synonym (#PCDATA)>
<!ATTLIST synonym
          xml:lang %Lang;  "en"
 >

<!-- Comments about the entry -->
<!ELEMENT comments (#PCDATA)>
<!ATTLIST comments
          xml:lang %Lang;  "en"
 >

<!-- Comment describing people who's worked on this entry -->
<!ELEMENT authors (#PCDATA)>

<!-- Date of the last entry uptade -->
<!ELEMENT date (#PCDATA)>

=== mchelen/blueobelisk/structures/trunk/src/nitroalkanes/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Nitroalkanes</title>
  <title xml:lang="de">Nitroalkan</title>
  <title xml:lang="es">Nitroalcanos</title>
  <title xml:lang="fr">Nitroalcanes</title>
  <title xml:lang="nl">Nitroalkanen</title>
  <entry id="CS_nitroethane">
    <name xml:lang="en">Nitroethane</name>
    <name xml:lang="fr">Nitroéthane</name>
    <filename>nitroethane</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_nitromethane">
    <name xml:lang="en">Nitromethane</name>
    <name xml:lang="fr">Nitrométhane</name>
    <filename>nitromethane</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/ethers/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Ethers</title>
  <title xml:lang="fr">Ethers</title>
  <title xml:lang="de">Ether</title>
  <entry id="CS_1_4-dioxane">
    <name xml:lang="en">1,4-Dioxane</name>
    <filename>1_4-dioxane</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_1-propoxypropane">
    <name xml:lang="en">1-Propoxypropane</name>
    <filename>1-propoxypropane</filename>
    <synonym xml:lang="en">Dipropylether</synonym>
    <synonym xml:lang="en">n-Propylether</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_2-methyl-2-tert-butoxypropane">
    <name xml:lang="en">2-Methyl-2-tert-butoxypropane</name>
    <filename>2-methyl-2-tert-butoxypropane</filename>
    <synonym xml:lang="en">Di-tert-butylether</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_1-butoxybutane">
    <name xml:lang="en">1-Butoxybutane</name>
    <filename>1-butoxybutane</filename>
    <synonym xml:lang="en">Dibutylether</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-06-26</date>
  </entry>
  <entry id="CS_2-propan-2-yloxypropane">
    <name xml:lang="en">2-Propan-2-yloxypropane</name>
    <filename>2-propan-2-yloxypropane</filename>
    <synonym xml:lang="en">Diisopropylether</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_ethoxyethane">
    <name xml:lang="en">Ethoxyethane</name>
    <filename>ethoxyethane</filename>
    <synonym xml:lang="en">Diethylether</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_furan">
    <name xml:lang="en">Furan</name>
    <filename>furan</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_methoxyethane">
    <name xml:lang="en">Methoxyethane</name>
    <filename>methoxyethane</filename>
    <synonym xml:lang="en">Ethylmethylether</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_methoxymethane">
    <name xml:lang="en">Methoxymethane</name>
    <filename>methoxymethane</filename>
    <synonym xml:lang="en">Dimethylether</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_oxolane">
    <name xml:lang="en">Oxolan</name>
    <filename>oxolane</filename>
    <synonym xml:lang="en">Tetrahydrofuran</synonym>
    <synonym xml:lang="en">Oxacyclopentane</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_2_3-dimethyloxepin">
    <name xml:lang="en">2,3-Dimethyloxepin</name>
    <filename>2_3-dimethyloxepin</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-13</date>
  </entry>
  <entry id="CS_2_7-dimethyloxepin">
    <name xml:lang="en">2,7-Dimethyloxepin</name>
    <filename>2_7-dimethyloxepin</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-13</date>
  </entry>
  <entry id="CS_oxepin">
    <name xml:lang="en">Oxepin</name>
    <filename>oxepin</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_R-2-ethoxybutane">
    <name xml:lang="en">(R)-2-Ethoxybutane</name>
    <filename>R-2-ethoxybutane</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_1_4_7_10_13_16-hexaoxacyclooctadecane">
    <name xml:lang="en">1,4,7,10,13,16-Hexaoxacyclooctadecane</name>
    <filename>1_4_7_10_13_16-hexaoxacyclooctadecane</filename>
    <synonym xml:lang="en">18-Crown-6 ether</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_2-2-hydroxyethoxy_ethanol">
    <name xml:lang="en">2-(2-Hydroxyethoxy)ethanol</name>
    <filename>2-2-hydroxyethoxy_ethanol</filename>
    <synonym xml:lang="en">Diethylene glycol</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/tags/2.2.0/trunk/src/amides/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Amides</title>
  <title xml:lang="de">Amide</title>
  <title xml:lang="es">Amidas</title>
  <title xml:lang="fr">Amides</title>
  <title xml:lang="nl">Amides</title>
  <title xml:lang="tw">Amides 醯胺</title>
  <entry id="CS_N_N-dimethylformamide">
    <name xml:lang="en">N,N-Dimethylformamide</name>
    <name xml:lang="de">N,N-Dimethylformamid</name>
    <name xml:lang="fr">N,N-Diméthylformamide</name>
    <name xml:lang="tw">N,N-Dimethylformamide N,N-二甲基甲醯胺</name>
    <filename>N_N-dimethylformamide</filename>
    <synonym xml:lang="en">DMF</synonym>
    <synonym xml:lang="de">DMF</synonym>
    <synonym xml:lang="fr">DMF</synonym>
    <synonym xml:lang="tw">DMF 二甲基甲醯胺</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_oxamide">
    <name xml:lang="en">Oxamide</name>
    <name xml:lang="de">Oxamid</name>
    <name xml:lang="fr">Oxamide</name>
    <name xml:lang="tw">Oxamide 草醯胺</name>
    <filename>oxamide</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_1-bromopyrrolidine-2_5-dione">
    <name xml:lang="en">1-Bromopyrrolidine-2,5-dione</name>
    <name xml:lang="fr">1-Bromopyrrolidine-2,5-dione</name>
    <name xml:lang="tw">1-Bromopyrrolidine-2,5-dione 1-溴吡咯烷-2,5-二酮</name>
    <filename>1-bromopyrrolidine-2_5-dione</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_acetamide">
    <name xml:lang="en">Acetamide</name>
    <name xml:lang="fr">Acétamide</name>
    <name xml:lang="tw">Acetamide 乙醯胺</name>
    <filename>acetamide</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_ethyl_carbamate">
    <name xml:lang="en">Ethyl carbamate</name>
    <name xml:lang="fr">Carbamate d'éthyle</name>
    <name xml:lang="tw">Ethyl carbamate 胺甲酸乙酯</name>
    <filename>ethyl_carbamate</filename>
    <synonym xml:lang="en">Urethane</synonym>
    <synonym xml:lang="fr">Uréthane</synonym>
    <synonym xml:lang="tw">Urethane 胺甲酸乙酯</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_N_N-dimethylacetamide">
    <name xml:lang="en">N,N-Dimethylacetamide</name>
    <name xml:lang="fr">N,N-Diméthylacétamide</name>
    <name xml:lang="tw">N,N-Dimethylacetamide N,N-二甲基乙醯胺</name>
    <filename>N_N-dimethylacetamide</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/tags/2.2.0/trunk/src/ethers/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Ethers</title>
  <title xml:lang="de">Ether</title>
  <title xml:lang="es">Éters</title>
  <title xml:lang="fr">Ethers</title>
  <title xml:lang="nl">Ethers</title>
  <title xml:lang="tw">Ethers 醚類</title>
  <entry id="CS_1_4-dioxane">
    <name xml:lang="en">1,4-Dioxane</name>
    <name xml:lang="fr">1,4-Dioxane</name>
    <name xml:lang="tw">1,4-Dioxane 1,4-二氧六環/二氧陸圜/二氧化二伸乙基</name>
    <filename>1_4-dioxane</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_1-propoxypropane">
    <name xml:lang="en">Dipropylether</name>
    <name xml:lang="fr">Dipropyléther</name>
    <name xml:lang="tw">Dipropylether 二丙醚</name>
    <filename>dipropylether</filename>
    <synonym xml:lang="en">1-Propoxypropane</synonym>
    <synonym xml:lang="en">n-Propylether</synonym>
    <synonym xml:lang="fr">1-Propoxypropane</synonym>
    <synonym xml:lang="fr">n-Propyléther</synonym>
    <synonym xml:lang="tw">1-Propoxypropane 1-丙氧丙烷/二丙醚</synonym>
    <synonym xml:lang="tw">n-Propylether 正-二丙醚</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_2-methyl-2-tert-butoxypropane">
    <name xml:lang="en">Di-tert-butylether</name>
    <name xml:lang="fr">Di-tert-butyléther</name>
    <name xml:lang="tw">Di-tert-butylether 二-第三丁醚</name>
    <filename>di-tert-butylether</filename>
    <synonym xml:lang="en">2-Methyl-2-tert-butoxypropane</synonym>
    <synonym xml:lang="fr">2-Méthyl-2-tert-butoxypropane</synonym>
    <synonym xml:lang="tw">2-Methyl-2-tert-butoxypropane 2-甲基-2-第三丁基醚</synonym>

    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_1-butoxybutane">
    <name xml:lang="en">Dibutylether</name>
    <name xml:lang="fr">Dibutyléther</name>
    <name xml:lang="tw">Dibutylether 二丁醚</name>
    <filename>dibutylether</filename>
    <synonym xml:lang="en">1-Butoxybutane</synonym>
    <synonym xml:lang="fr">1-Butoxybutane</synonym>
    <synonym xml:lang="tw">1-Butoxybutane 1-丁基醚</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-06-26</date>
  </entry>
  <entry id="CS_2-propan-2-yloxypropane">
    <name xml:lang="en">Diisopropylether</name>
    <name xml:lang="fr">Diisopropyléther</name>
    <name xml:lang="tw">Diisopropylether 二異丙醚</name>
    <filename>diisopropylether</filename>
    <synonym xml:lang="en">2-Propan-2-yloxypropane</synonym>
    <synonym xml:lang="fr">2-Propan-2-yloxypropane</synonym>
    <synonym xml:lang="tw">2-Propan-2-yloxypropane 二異丙醚</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_ethoxyethane">
    <name xml:lang="en">Diethylether</name>
    <name xml:lang="fr">Diéthyléther</name>
    <name xml:lang="tw">Diethylether 二乙醚</name>
    <filename>diethylether</filename>
    <synonym xml:lang="en">Ethoxyethane</synonym>
    <synonym xml:lang="en">Ether</synonym>
    <synonym xml:lang="fr">Ethoxyéthane</synonym>
    <synonym xml:lang="fr">Ether</synonym>
    <synonym xml:lang="tw">Ethoxyethane 二乙醚</synonym>
    <synonym xml:lang="tw">Ether 醚</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_furan">
    <name xml:lang="en">Furan</name>
    <name xml:lang="fr">Furane</name>
    <name xml:lang="tw">Furan 呋喃</name>
    <filename>furan</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_methoxyethane">
    <name xml:lang="en">Ethylmethylether</name>
    <name xml:lang="fr">Ethylméthyléther</name>
    <name xml:lang="tw">Ethylmethylether 甲乙醚</name>
    <filename>ethylmethylether</filename>
    <synonym xml:lang="en">Methoxyethane</synonym>
    <synonym xml:lang="fr">Méthoxyéthane</synonym>
    <synonym xml:lang="tw">Methoxyethane 甲乙醚</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_methoxymethane">
    <name xml:lang="en">Dimethylether</name>
    <name xml:lang="fr">Diméthyléther</name>
    <name xml:lang="tw">Dimethylether 二甲醚</name>
    <filename>dimethylether</filename>
    <synonym xml:lang="en">Methoxymethane</synonym>
    <synonym xml:lang="fr">Méthoxyméthane</synonym>
    <synonym xml:lang="tw">Methoxymethane 二甲醚</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_oxacyclopentane">
    <name xml:lang="en">Tetrahydrofuran</name>
    <name xml:lang="fr">Tétrahydrofurane</name>
    <name xml:lang="tw">Tetrahydrofuran 四氫呋喃 (縮寫為 THF)</name>
    <filename>tetrahydrofuran</filename>
    <synonym xml:lang="en">Oxacyclopentane</synonym>
    <synonym xml:lang="en">Oxolane</synonym>
    <synonym xml:lang="fr">Oxacyclopentane</synonym>
    <synonym xml:lang="fr">Oxolane</synonym>
    <synonym xml:lang="tw">Oxacyclopentane 四氫呋喃/氧雜環戊烷</synonym>
    <synonym xml:lang="tw">Oxolane 四氫呋喃/氧雜環戊烷</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_2_3-dimethyloxepin">
    <name xml:lang="en">2,3-Dimethyloxepin</name>
    <name xml:lang="fr">2,3-Diméthyloxépine</name>
    <name xml:lang="tw">2,3-Dimethyloxepin 暫譯為: 2,3-二甲基一氧柒圜/二甲基七員環醚</name>
    <filename>2_3-dimethyloxepin</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-13</date>
  </entry>
  <entry id="CS_2_7-dimethyloxepin">
    <name xml:lang="en">2,7-Dimethyloxepin</name>
    <name xml:lang="fr">2,7-Diméthyloxépine</name>
    <name xml:lang="tw">2,7-Dimethyloxepin 暫譯為: 2,7-二甲基一氧柒圜/二甲基七員環醚</name>
    <filename>2_7-dimethyloxepin</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-13</date>
  </entry>
  <entry id="CS_oxepin">
    <name xml:lang="en">Oxepin</name>
    <name xml:lang="fr">Oxépine</name>
    <name xml:lang="tw">Oxepin 暫譯為: 一氧柒圜/七員環醚</name>
    <filename>oxepin</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_R-2-ethoxybutane">
    <name xml:lang="en">(R)-2-Ethoxybutane</name>
    <name xml:lang="fr">(R)-2-Ethoxybutane</name>
    <name xml:lang="tw">(R)-2-Ethoxybutane (R)-2-乙氧基丁烷</name>
    <filename>R-2-ethoxybutane</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-09</date>
  </entry>
  <entry id="CS_1_4_7_10_13_16-hexaoxacyclooctadecane">
    <name xml:lang="en">1,4,7,10,13,16-Hexaoxacyclooctadecane</name>
    <name xml:lang="fr">1,4,7,10,13,16-Hexaoxacyclooctadécane</name>
    <name xml:lang="tw">1,4,7,10,13,16-Hexaoxacyclooctadecane 1,4,7,10,13,16-六氧環十八烷</name>
    <filename>1_4_7_10_13_16-hexaoxacyclooctadecane</filename>
    <synonym xml:lang="en">18-Crown-6 ether</synonym>
    <synonym xml:lang="fr">Ether 18-couronne-6</synonym>
    <synonym xml:lang="tw">18-Crown-6 ether 冠狀環醚 18-Crown-6 (18 員環, 6 個氧)</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_2-2-hydroxyethoxy_ethanol">
    <name xml:lang="en">2-(2-Hydroxyethoxy)ethanol</name>
    <name xml:lang="fr">2-(2-Hydroxyéthoxy)éthanol</name>
    <name xml:lang="tw">2-(2-Hydroxyethoxy)ethanol 2-(2-羥基乙氧基)乙醇</name>
    <filename>2-2-hydroxyethoxy_ethanol</filename>
    <synonym xml:lang="en">Diethylene glycol</synonym>
    <synonym xml:lang="fr">Diéthylène glycol</synonym>
    <synonym xml:lang="tw">Diethylene glycol 二乙二醇/二甘醇</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_tetrahydropyran">
    <name xml:lang="en">Tetrahydropyran</name>
    <name xml:lang="fr">Tétrahydropyrane</name>
    <name xml:lang="tw">Tetrahydropyran 四氫吡喃</name>
    <filename>tetrahydropyran</filename>
    <synonym xml:lang="en">Oxane</synonym>
    <synonym xml:lang="en">Oxacyclohexane</synonym>
    <synonym xml:lang="fr">Oxane</synonym>
    <synonym xml:lang="fr">Oxacyclohexane</synonym>
    <synonym xml:lang="tw">Oxane 暫譯: 氧烷</synonym>
    <synonym xml:lang="tw">Oxacyclohexane 暫譯: 氧環己烷</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2009-07-06</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/sulfoxides/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Sulfoxides</title>
  <title xml:lang="fr">Sulfoxydes</title>
  <title xml:lang="de">Sulfoxide</title>
  <entry id="CS_methylsulfinylmethane">
    <name xml:lang="en">Methylsulfinylmethane</name>
    <filename>methylsulfinylmethane</filename>
    <synonym xml:lang="en">Dimethylsulfoxyde</synonym>
    <synonym xml:lang="fr">Dim√©thylsulfoxyde</synonym>
    <synonym xml:lang="en">DMSO</synonym>
    <synonym xml:lang="fr">DMSO</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/fatty_acids/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Fatty acids</title>
  <title xml:lang="fr">Acides gras</title>
  <title xml:lang="de">Fettsäuren</title>
  <entry id="CS_4Z_7Z_10Z_13Z_16Z_19Z-docosa-4_7_10_13_16_19-hexaenoic_acid">
    <name xml:lang="en">(4Z,7Z,10Z,13Z,16Z,19Z)-Docosa-4,7,10,13,16,19-hexaenoic acid</name>
    <filename>4Z_7Z_10Z_13Z_16Z_19Z-docosa-4_7_10_13_16_19-hexaenoic_acid</filename>
    <synonym xml:lang="en">Cervonic acid</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_5Z_8Z_11Z_14Z_17Z-icosa-5_8_11_14_17-pentaenoic_acid">
    <name xml:lang="en">(5Z,8Z,11Z,14Z,17Z)-Icosa-5,8,11,14,17-pentaenoic acid</name>
    <filename>5Z_8Z_11Z_14Z_17Z-icosa-5_8_11_14_17-pentaenoic_acid</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_5Z_8Z_11Z_14Z-icosa-5_8_11_14-tetraenoic_acid">
    <name xml:lang="en">(5Z,8Z,11Z,14Z)-Icosa-5,8,11,14-tetraenoic acid</name>
    <filename>5Z_8Z_11Z_14Z-icosa-5_8_11_14-tetraenoic_acid</filename>
    <synonym xml:lang="en">Arachidonic acid</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_6Z_9Z_12Z-octadeca-6_9_12-trienoic_acid">
    <name xml:lang="en">(6Z,9Z,12Z)-Octadeca-6,9,12-trienoic acid</name>
    <filename>6Z_9Z_12Z-octadeca-6_9_12-trienoic_acid</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_9Z_12Z_15Z-octadeca-9_12_15-trienoic_acid">
    <name xml:lang="en">(9Z,12Z,15Z)-Octadeca-9,12,15-trienoic acid</name>
    <filename>9Z_12Z_15Z-octadeca-9_12_15-trienoic_acid</filename>
    <synonym xml:lang="en">Linolenic acid</synonym>
    <synonym xml:lang="fr">Acide linolénique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_octadecanoic_acid">
    <name xml:lang="en">Octadecanoic acid</name>
    <filename>octadecanoic_acid</filename>
    <synonym xml:lang="en">Stearic acid</synonym>
    <synonym xml:lang="fr">Acide stéarique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_Z-octadec-9-enoic_acid">
    <name xml:lang="en">(Z)-Octadec-9-enoic acid</name>
    <filename>Z-octadec-9-enoic_acid</filename>
    <synonym xml:lang="en">Oleic acid</synonym>
    <synonym xml:lang="fr">Acide oléique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_pentanoic_acid">
    <name xml:lang="en">Pentanoic acid</name>
    <filename>pentanoic_acid</filename>
    <synonym xml:lang="en">Valerianic acid</synonym>
    <synonym xml:lang="en">Valeric acid</synonym>
    <synonym xml:lang="fr">Acide valérique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_hexanoic_acid">
    <name xml:lang="en">Hexanoic acid</name>
    <filename>hexanoic_acid</filename>
    <synonym xml:lang="en">Caproic acid</synonym>
    <synonym xml:lang="fr">Acide caproïque</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_heptanoic_acid">
    <name xml:lang="en">Heptanoic acid</name>
    <filename>heptanoic_acid</filename>
    <synonym xml:lang="en">Enanthic acid</synonym>
    <synonym xml:lang="fr">Acide énanthique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_octanoic_acid">
    <name xml:lang="en">Octanoic acid</name>
    <filename>octanoic_acid</filename>
    <synonym xml:lang="en">Caprylic acid</synonym>
    <synonym xml:lang="fr">Acide caprylique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_decanoic_acid">
    <name xml:lang="en">Decanoic acid</name>
    <filename>decanoic_acid</filename>
    <synonym xml:lang="en">Caprinic acid</synonym>
    <synonym xml:lang="fr">Acide caprinique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_dodecanoic_acid">
    <name xml:lang="en">Dodecanoic acid</name>
    <filename>dodecanoic_acid</filename>
    <synonym xml:lang="en">Lauric acid</synonym>
    <synonym xml:lang="fr">Acide laurique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_tetradecanoic_acid">
    <name xml:lang="en">Tetradecanoic acid</name>
    <filename>tetradecanoic_acid</filename>
    <synonym xml:lang="en">Myristic acid</synonym>
    <synonym xml:lang="fr">Acide myristique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_hexadecanoic_acid">
    <name xml:lang="en">Hexadecanoic acid</name>
    <filename>hexadecanoic_acid</filename>
    <synonym xml:lang="en">Palmitic acid</synonym>
    <synonym xml:lang="fr">Acide palmitique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-11</date>
  </entry>
  <entry id="CS_9Z_12Z-octadeca-9_12-dienoic_acid">
    <name xml:lang="en">(9Z,12Z)-Octadeca-9,12-dienoic acid</name>
    <filename>9Z_12Z-octadeca-9_12-dienoic_acid</filename>
    <synonym xml:lang="en">Linoleic acid</synonym>
    <synonym xml:lang="fr">Acide linoléique</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
</index>

=== mchelen/blueobelisk/structures/trunk/src/ketones/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//CHEMSTRUCT//DTD Index 1.0//EN" "index.dtd">
<index>
  <title xml:lang="en">Ketones</title>
  <title xml:lang="fr">Cétones</title>
  <title xml:lang="de">Ketone</title>
  <entry id="CS_butanone">
    <name xml:lang="en">Butanone</name>
    <filename>butanone</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_heptan-2-one">
    <name xml:lang="en">Heptan-2-one</name>
    <filename>heptan-2-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_heptan-3-one">
    <name xml:lang="en">Heptan-3-one</name>
    <filename>heptan-3-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_heptan-4-one">
    <name xml:lang="en">Heptan-4-one</name>
    <filename>heptan-4-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_hexan-2-one">
    <name xml:lang="en">Hexan-2-one</name>
    <filename>hexan-2-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_hexan-3-one">
    <name xml:lang="en">Hexan-3-one</name>
    <filename>hexan-3-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_octan-2-one">
    <name xml:lang="en">Octan-2-one</name>
    <filename>octan-2-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_octan-3-one">
    <name xml:lang="en">Octan-3-one</name>
    <filename>octan-3-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_octan-4-one">
    <name xml:lang="en">Octan-4-one</name>
    <filename>octan-4-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_pentan-2-one">
    <name xml:lang="en">Pentan-2-one</name>
    <filename>pentan-2-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_pentan-3-one">
    <name xml:lang="en">Pentan-3-one</name>
    <filename>pentan-3-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_propanone">
    <name xml:lang="en">Propanone</name>
    <filename>propanone</filename>
    <synonym xml:lang="en">Aceton</synonym>
    <synonym xml:lang="fr">Acétone</synonym>
    <synonym xml:lang="fr">Diméthylcétone</synonym>
    <synonym xml:lang="de">Aceton</synonym>
    <synonym xml:lang="de">Dimethylketon</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-05-10</date>
  </entry>
  <entry id="CS_cyclohexa-2_5-diene-1_4-dione">
    <name xml:lang="en">Cyclohexa-2,5-diene-1,4-dione</name>
    <filename>cyclohexa-2_5-diene-1_4-dione</filename>
    <synonym xml:lang="en">Quinone</synonym>
    <synonym xml:lang="en">p-Benzoquinone</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-06-29</date>
  </entry>
  <entry id="CS_cyclohexa-2_4-diene-1_6-dione">
    <name xml:lang="en">Cyclohexa-2,4-diene-1,6-dione</name>
    <filename>cyclohexa-2_4-diene-1_6-dione</filename>
    <synonym xml:lang="en">o-Quinone</synonym>
    <synonym xml:lang="en">o-Benzoquinone</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-06-29</date>
  </entry>
  <entry id="CS_cyclopentanone">
    <name xml:lang="en">Cyclopentanone</name>
    <filename>cyclopentanone</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_pyran-2-one">
    <name xml:lang="en">Pyran-2-one</name>
    <filename>pyran-2-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_pyran-4-one">
    <name xml:lang="en">Pyran-4-one</name>
    <filename>pyran-4-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-07-31</date>
  </entry>
  <entry id="CS_1_1_1_3_3_3-hexafluoropropanone">
    <name xml:lang="en">1,1,1,3,3,3-Hexafluoropropanone</name>
    <filename>1_1_1_3_3_3-hexafluoropropanone</filename>
    <synonym xml:lang="en">Hexafluoroacetone</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_Z-4-hydroxypent-3-en-2-one">
    <name xml:lang="en">(Z)-4-Hydroxypent-3-en-2-one</name>
    <filename>Z-4-hydroxypent-3-en-2-one</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_but-3-en-2-one">
    <name xml:lang="en">But-3-en-2-one</name>
    <filename>but-3-en-2-one</filename>
    <synonym xml:lang="en">3-Buten-2-one</synonym>
    <synonym xml:lang="en">Methyl vinyl ketone</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_cyclohex-2-en-1-one">
    <name xml:lang="en">Cyclohex-2-en-1-one</name>
    <filename>cyclohex-2-en-1-one</filename>
    <synonym xml:lang="en">2-Cyclohexen-1-one</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_cyclohexanone">
    <name xml:lang="en">Cyclohexanone</name>
    <filename>cyclohexanone</filename>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
  <entry id="CS_cyclopent-2-en-1-one">
    <name xml:lang="en">Cyclopent-2-en-1-one</name>
    <filename>cyclopent-2-en-1-one</filename>
    <synonym xml:lang="en">2-Cyclopenten-1-one</synonym>
    <authors>Jerome Pansanel</authors>
    <date>2006-11-22</date>
  </entry>
</index>
